CREATE TABLE Car
(
	CarId DECIMAL(7) NOT NULL IDENTITY(1,1),
	PointRequirement INT NOT NULL,
	ViewResourcesPath VARCHAR(MAX) NOT NULL,
	CONSTRAINT Cars_PK PRIMARY KEY(CarId)
);

CREATE TABLE Player
(
	PlayerId DECIMAL(7) NOT NULL IDENTITY(1,1),
	Username VARCHAR(20) NOT NULL,
	PW BINARY(16) NOT NULL,
	Highscore INT,
	IsAdmin BIT NOT NULL,
	CarId DECIMAL(7) NOT NULL
	CONSTRAINT Player_PK PRIMARY KEY(PlayerId),
	CONSTRAINT Car_FK FOREIGN KEY(CarId) REFERENCES Car(CarId)
);