//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HighwayCoaster.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    /// <summary>
    /// Database entities
    /// </summary>
    public partial class HighwayCoasterDatabaseEntities : DbContext
    {
        /// <summary>
        /// Constructor for highway coaster DB entities
        /// </summary>
        public HighwayCoasterDatabaseEntities()
            : base("name=HighwayCoasterDatabaseEntities")
        {
        }
    
        /// <summary>
        /// On model creating
        /// </summary>
        /// <param name="modelBuilder">model builder</param>
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        /// <summary>
        /// Gets or sets car
        /// </summary>
        public virtual DbSet<Car> Car { get; set; }

        /// <summary>
        /// Gets or sets Player
        /// </summary>
        public virtual DbSet<Player> Player { get; set; }
    }
}
