//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HighwayCoaster.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public decimal PlayerId { get; set; }
        public string Username { get; set; }
        public byte[] PW { get; set; }
        public Nullable<int> Highscore { get; set; }
        public bool IsAdmin { get; set; }
        public decimal CarId { get; set; }
    
        public virtual Car Car { get; set; }
    }
}
